import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type",
};

const FUNCTION_BASE_URL = "https://koqpbnxkhgbsnbdjwldx.supabase.co/functions/v1";

// Inject a 1×1 tracking pixel before </body>. Falls back to appending.
function injectPixel(html: string, token: string): string {
  const pixel = `<img src="${FUNCTION_BASE_URL}/email-webhook/pixel/${token}" `
    + `width="1" height="1" style="display:none" alt="">`;
  return html.includes("</body>")
    ? html.replace("</body>", `${pixel}</body>`)
    : html + pixel;
}

// Wrap all absolute href links with a click-tracking redirect URL.
// Handles both double-quoted and single-quoted href attributes.
function wrapLinks(html: string, token: string): string {
  return html.replace(
    /href=(["'])(https?:\/\/[^"']+)\1/gi,
    (_, q, url) =>
      `href=${q}${FUNCTION_BASE_URL}/email-webhook/click/${token}?url=${encodeURIComponent(url)}${q}`
  );
}

// ── Main handler ──────────────────────────────────────────────────────────────

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  const apiKey = Deno.env.get("RESEND_API_KEY");
const FROM_EMAIL = Deno.env.get("RESEND_FROM_EMAIL") || "zach@roofingos.dev";
const FROM_NAME  = Deno.env.get("RESEND_FROM_NAME")  || "Zach @ Roofing OS";

  if (!apiKey) {
    return new Response(
      JSON.stringify({ error: "RESEND_API_KEY secret not configured" }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }

  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!
  );

  try {
    const body = await req.json();
    const {
      lead_id, enrollment_id, step_id, email_template_id,
      to_email, subject, body_html, body_text,
      client_id, from_name,
    } = body;

    if (!lead_id || !enrollment_id || !step_id || !email_template_id) {
      return bad("lead_id, enrollment_id, step_id, email_template_id required");
    }
    if (!to_email || !subject || !body_html || !body_text || !client_id) {
      return bad("to_email, subject, body_html, body_text, client_id required");
    }

    // Insert email_sends row. tracking_token is generated by DB default.
    // body_html stored clean (pre-tracking) as the canonical snapshot.
    const { data: row, error: insertErr } = await supabase
      .from("email_sends")
      .insert({ lead_id, enrollment_id, step_id, email_template_id, to_email, subject, body_html })
      .select("id, tracking_token")
      .single();

    if (insertErr || !row) {
      return bad(`Failed to create email_sends record: ${insertErr?.message}`);
    }

    const { id: emailSendId, tracking_token: token } = row as { id: string; tracking_token: string };

    // Build tracked HTML — pixel + click wrapping.
    const trackedHtml = injectPixel(wrapLinks(body_html as string, token), token);

    const sender = `${FROM_NAME} <${FROM_EMAIL}>`;

    const resendRes = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${apiKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: sender,
        to: [to_email],
        reply_to: FROM_EMAIL,
        subject,
        html: trackedHtml,
        text: body_text,
        // Tag embeds tracking_token in all Resend webhook payloads for reliable matching.
        tags: [{ name: "tracking_token", value: token }],
      }),
    });

    if (!resendRes.ok) {
      // Delete the phantom row so it doesn't pollute the send history.
      await supabase.from("email_sends").delete().eq("id", emailSendId);
      const resendErr = await resendRes.json().catch(() => ({})) as Record<string, unknown>;
      return bad(`Resend error ${resendRes.status}: ${resendErr.message ?? resendRes.statusText}`);
    }

    // Store post-tracking HTML (with pixel + click links) as the canonical snapshot.
    await supabase
      .from("email_sends")
      .update({ body_html: trackedHtml, sent_at: new Date().toISOString() })
      .eq("id", emailSendId);

    return ok({ success: true, email_send_id: emailSendId, tracking_token: token });

  } catch (err) {
    console.error("send-email error:", err);
    return new Response(
      JSON.stringify({ error: (err as Error).message || String(err) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});

function ok(data: unknown) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}

function bad(msg: string) {
  return new Response(JSON.stringify({ error: msg }), {
    status: 400,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
