-- Migration 025: Seed 300 roofing prospects + 200 Nexus outbound prospects
-- Roofing prospects: CO(50), TX(75), FL(50), GA(40), OH(45), IL(40)
-- Nexus outbound: multi-venture operators and agency owners (200)

-- ── COLORADO (50) ─────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'CO', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Peak Roofing Solutions','Jason Miller','303','Denver'),
 ('Rocky Mountain Roofing','Brian Torres','720','Denver'),
 ('Colorado Roofing Experts','Kevin Walsh','303','Denver'),
 ('Front Range Roofing LLC','Scott Anderson','720','Denver'),
 ('Denver Roofing Pros','Mark Phillips','303','Denver'),
 ('Mile High Roofing','Ryan Nelson','720','Aurora'),
 ('Summit Roofing Group','Chad Davis','303','Aurora'),
 ('Alpine Roofing Co','Derek Martin','720','Lakewood'),
 ('Centennial Roofing','Tyler Johnson','303','Lakewood'),
 ('High Country Roofing','Austin Brown','720','Denver'),
 ('Pinnacle Roofing Co','Nathan Wilson','303','Denver'),
 ('Colorado Storm Pros','Greg Campbell','720','Denver'),
 ('Foothill Roofing','Mike Harrison','303','Arvada'),
 ('Denver Metro Roofing','Chris Roberts','720','Arvada'),
 ('5280 Roofing','Alex Thompson','303','Denver'),
 ('Colorado Hail Pro','Dan Williams','719','Colorado Springs'),
 ('Rockies Roofing Group','Jeff Clark','719','Colorado Springs'),
 ('Clear Creek Roofing','Eric Lewis','303','Golden'),
 ('Red Rocks Roofing','Matt Robinson','303','Morrison'),
 ('Pikes Peak Roofing','Steve Walker','719','Colorado Springs'),
 ('Mesa View Roofing','Todd Hall','719','Colorado Springs'),
 ('Denver Roof Specialists','Brandon Allen','720','Denver'),
 ('Mountain West Roofing','Jeremy Young','303','Westminster'),
 ('Columbine Roofing','Shane Hernandez','303','Littleton'),
 ('Arapahoe Roofing','Kyle King','303','Englewood'),
 ('South Metro Roofing','Derek Wright','303','Centennial'),
 ('Heritage Roofing Co','Ryan Lopez','303','Highlands Ranch'),
 ('Altitude Roofing LLC','Travis Hill','720','Castle Rock'),
 ('Apex Roofing Denver','Austin Scott','303','Denver'),
 ('Continental Roofing','Chad Green','720','Denver'),
 ('Lakewood Roof Pro','Jordan Adams','303','Lakewood'),
 ('Castle Rock Roofing','Blake Turner','303','Castle Rock'),
 ('Thornton Roofing','Cody White','720','Thornton'),
 ('Brighton Roofing Co','Derek Harris','303','Brighton'),
 ('Loveland Roofing','Ryan Thompson','970','Loveland'),
 ('Fort Collins Roof Co','Austin Lewis','970','Fort Collins'),
 ('Greeley Roofing Pro','Chase Moore','970','Greeley'),
 ('Westminster Roof Co','Garrett Jackson','303','Westminster'),
 ('Broomfield Roofing','Tyler Taylor','303','Broomfield'),
 ('Northside Roofing','Brandon Martin','303','Northglenn'),
 ('Trident Roofing','Zach Curtis','720','Denver'),
 ('Gold Hill Roofing','Mike Lewis','303','Boulder'),
 ('Boulder Roofing Pro','Kyle Martinez','303','Boulder'),
 ('Lariat Roofing','Jason Brown','720','Parker'),
 ('Douglas County Roofing','Blake Wilson','303','Parker'),
 ('Sky Ridge Roofing','Chris Davis','303','Aurora'),
 ('Meridian Roofing','Derek Jones','720','Meridian'),
 ('Tri-County Roofing','Matt Garcia','303','Longmont'),
 ('Allstate Roof Pros','Brian Miller','720','Denver'),
 ('Summit Storm Roofing','Logan Baker','303','Denver')
) AS t(c,n,ac,city);

-- ── TEXAS (75) ────────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'TX', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Lone Star Roofing','Carlos Reyes','214','Dallas'),
 ('DFW Roofing Pros','Kevin James','817','Fort Worth'),
 ('Texas Storm Shield','Marcus Williams','972','Plano'),
 ('Dallas Roofing Co','Tony Hernandez','214','Dallas'),
 ('Premier Roofing TX','James Carter','817','Arlington'),
 ('Metroplex Roofing','Robert Davis','972','Irving'),
 ('Texan Roofing Group','Brandon Lee','214','Dallas'),
 ('North Texas Roofing','Chris Martinez','817','Keller'),
 ('Cowboy Roofing LLC','Derek Wilson','972','Garland'),
 ('Lone Star Storm Pro','Ryan Phillips','214','Dallas'),
 ('Dallas Elite Roofing','Anthony Brown','817','Fort Worth'),
 ('Southlake Roofing','Greg Thompson','817','Southlake'),
 ('Mansfield Roofing Co','Jason Scott','817','Mansfield'),
 ('Grand Prairie Roof','Mike Johnson','972','Grand Prairie'),
 ('Mesquite Roofing','Chad Anderson','972','Mesquite'),
 ('Frisco Roofing Pro','Tyler Roberts','972','Frisco'),
 ('McKinney Roofing','Austin Turner','469','McKinney'),
 ('Allen Roofing Group','Blake Walker','469','Allen'),
 ('Rockwall Roofing','Shane Young','972','Rockwall'),
 ('Denton Roofing Pro','Nathan Hall','940','Denton'),
 ('Houston Roofing Co','Eduardo Garcia','713','Houston'),
 ('Gulf Coast Roofing','Luis Morales','832','Houston'),
 ('H-Town Roofing','Jose Rodriguez','713','Houston'),
 ('Houston Storm Pro','Miguel Sanchez','832','Houston'),
 ('Memorial Roofing','Andrew Kim','713','Houston'),
 ('Katy Roofing Group','Steven Chen','281','Katy'),
 ('Sugar Land Roofing','David Nguyen','281','Sugar Land'),
 ('Pearland Roofing','Mark Patel','713','Pearland'),
 ('The Woodlands Roof','Kevin Walsh','281','The Woodlands'),
 ('Cypress Roofing Pro','Brian Hall','832','Cypress'),
 ('Spring Roofing LLC','Jason Moore','281','Spring'),
 ('Humble Roofing Co','Ryan Davis','281','Humble'),
 ('Pasadena Roof Pro','Carlos Rivera','713','Pasadena'),
 ('Conroe Roofing','Derek Stewart','936','Conroe'),
 ('Baytown Roofing','Tony Lewis','281','Baytown'),
 ('Austin Roofing Co','Matt Sullivan','512','Austin'),
 ('Capital Roofing TX','Chris O''Brien','512','Austin'),
 ('Round Rock Roofing','Patrick Murphy','512','Round Rock'),
 ('Cedar Park Roof','Sean Kelly','512','Cedar Park'),
 ('Georgetown Roofing','Ryan Burke','512','Georgetown'),
 ('Pflugerville Roof','Mike Quinn','512','Pflugerville'),
 ('San Antonio Roofing','Jose Gutierrez','210','San Antonio'),
 ('Alamo City Roofing','Ricardo Flores','210','San Antonio'),
 ('SA Storm Shield','Diego Ramirez','210','San Antonio'),
 ('NE San Antonio Roof','Carlos Cruz','210','San Antonio'),
 ('Leon Valley Roofing','Victor Torres','210','Leon Valley'),
 ('Converse Roofing','Juan Medina','210','Converse'),
 ('Schertz Roofing Co','Angel Gomez','210','Schertz'),
 ('New Braunfels Roof','Pablo Jimenez','830','New Braunfels'),
 ('Laredo Roofing Pro','Roberto Reyes','956','Laredo'),
 ('McAllen Roofing','Fernando Soto','956','McAllen'),
 ('Corpus Christi Roof','Daniel Castillo','361','Corpus Christi'),
 ('Lubbock Roofing Co','Tyler Adams','806','Lubbock'),
 ('Amarillo Roof Pro','Chase Parker','806','Amarillo'),
 ('Waco Roofing LLC','Travis Evans','254','Waco'),
 ('Abilene Roofing','Cody Mitchell','325','Abilene'),
 ('Tyler Roofing Co','Brandon Hayes','903','Tyler'),
 ('Beaumont Roofing','Kevin Bryant','409','Beaumont'),
 ('Midland Roofing','Logan Gibson','432','Midland'),
 ('Odessa Roof Pro','Nathan Ellis','432','Odessa'),
 ('El Paso Roofing','Marco Rodriguez','915','El Paso'),
 ('Plano Roofing Pros','Scott Freeman','469','Plano'),
 ('Carrollton Roofing','Derek Burns','972','Carrollton'),
 ('Richardson Roof Co','Alex Wells','972','Richardson'),
 ('Lewisville Roofing','Jordan Ford','972','Lewisville'),
 ('Flower Mound Roof','Garrett Barnes','972','Flower Mound'),
 ('Grapevine Roofing','Blake Hamilton','817','Grapevine'),
 ('Euless Roof Pro','Cody Ross','817','Euless'),
 ('Hurst Roofing LLC','Tyler Mason','817','Hurst'),
 ('Bedford Roofing','Austin Bell','817','Bedford'),
 ('Colleyville Roof','Shane Murray','817','Colleyville'),
 ('Weatherford Roofing','Derek Cole','817','Weatherford'),
 ('Burleson Roofing','Ryan Harvey','817','Burleson'),
 ('Cleburne Roof Pro','Travis Price','817','Cleburne'),
 ('Waxahachie Roofing','Jason Long','972','Waxahachie'),
 ('Ennis Roofing Co','Mike Powell','972','Ennis')
) AS t(c,n,ac,city);

-- ── FLORIDA (50) ──────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'FL', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Sunshine State Roofing','Carlos Mendez','813','Tampa'),
 ('Bay Area Roofing FL','Kevin Santos','727','Tampa'),
 ('Tampa Bay Roof Co','Luis Ortega','813','Tampa'),
 ('Gulf Roofing Pros','Marco Rivera','813','Tampa'),
 ('Hillsborough Roofing','Diego Vargas','813','Tampa'),
 ('Brandon Roofing LLC','Jose Perez','813','Brandon'),
 ('Riverview Roof Pro','Miguel Castro','813','Riverview'),
 ('Clearwater Roofing','Angel Flores','727','Clearwater'),
 ('St Pete Roofing','Ricardo Diaz','727','St Petersburg'),
 ('Largo Roofing Co','Fernando Moreno','727','Largo'),
 ('Dunedin Roof Pro','Roberto Jimenez','727','Dunedin'),
 ('New Port Roofing','Pablo Torres','727','New Port Richey'),
 ('Sarasota Roofing','Eduardo Romero','941','Sarasota'),
 ('Bradenton Roof Co','Victor Ruiz','941','Bradenton'),
 ('Venice Roofing LLC','Daniel Navarro','941','Venice'),
 ('Orlando Roofing Pro','James Wilson','407','Orlando'),
 ('Central FL Roofing','Ryan Thompson','407','Orlando'),
 ('Kissimmee Roofing','Derek Brown','407','Kissimmee'),
 ('Osceola Roof Co','Tyler Davis','407','Kissimmee'),
 ('Lake Mary Roofing','Austin Clark','407','Lake Mary'),
 ('Sanford Roofing','Brandon Lewis','407','Sanford'),
 ('Altamonte Roofing','Mike Johnson','407','Altamonte Springs'),
 ('Winter Park Roof','Jason White','407','Winter Park'),
 ('Maitland Roofing','Chad Martin','407','Maitland'),
 ('Windermere Roof','Greg Anderson','407','Windermere'),
 ('Miami Roofing Co','Alejandro Vega','305','Miami'),
 ('South Florida Roof','Roberto Blanco','305','Miami'),
 ('Coral Gables Roof','Carlos Reyes','305','Coral Gables'),
 ('Hialeah Roofing','Jose Rodriguez','305','Hialeah'),
 ('Doral Roofing Pro','Miguel Garcia','305','Doral'),
 ('Pembroke Pines Roof','Luis Morales','954','Pembroke Pines'),
 ('Hollywood FL Roofing','Ricardo Gutierrez','954','Hollywood'),
 ('Plantation Roofing','Angel Hernandez','954','Plantation'),
 ('Fort Lauderdale Roof','Victor Martinez','954','Fort Lauderdale'),
 ('Boca Raton Roofing','Fernando Torres','561','Boca Raton'),
 ('Palm Beach Roofing','Eduardo Sanchez','561','West Palm Beach'),
 ('Boynton Roofing','Marco Diaz','561','Boynton Beach'),
 ('Delray Roofing Co','Diego Cruz','561','Delray Beach'),
 ('Jax Roofing Pros','Billy Harris','904','Jacksonville'),
 ('First Coast Roofing','Tommy Nelson','904','Jacksonville'),
 ('Fleming Island Roof','Bobby Evans','904','Fleming Island'),
 ('Orange Park Roof','Jimmy Watson','904','Orange Park'),
 ('St Augustine Roof','Danny Cooper','904','St Augustine'),
 ('Gainesville Roofing','Brian Foster','352','Gainesville'),
 ('Ocala Roof Pro','Steve Griffin','352','Ocala'),
 ('Daytona Roofing','Mark Reed','386','Daytona Beach'),
 ('Port Orange Roof','Jeff Bailey','386','Port Orange'),
 ('Tallahassee Roof','Scott Price','850','Tallahassee'),
 ('Pensacola Roofing','Kevin Long','850','Pensacola'),
 ('Fort Myers Roofing','Chris Simmons','239','Fort Myers')
) AS t(c,n,ac,city);

-- ── GEORGIA (40) ─────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'GA', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Atlanta Roofing Pros','Darius Jackson','404','Atlanta'),
 ('Georgia Storm Shield','Marcus Brown','678','Atlanta'),
 ('Peach State Roofing','Terrell Williams','404','Atlanta'),
 ('ATL Roofing Co','Jamal Davis','470','Atlanta'),
 ('Metro Atlanta Roof','DeShawn Harris','404','Atlanta'),
 ('Buckhead Roofing','Kevin Thompson','404','Atlanta'),
 ('Midtown Roof Co','Brian Mitchell','404','Atlanta'),
 ('East Atlanta Roof','Derrick Robinson','404','Atlanta'),
 ('Smyrna Roofing LLC','Corey Walker','770','Smyrna'),
 ('Kennesaw Roofing','Andre Lewis','770','Kennesaw'),
 ('Marietta Roof Pros','Reggie Clark','770','Marietta'),
 ('Cobb County Roofing','Terrence Johnson','770','Marietta'),
 ('Roswell Roofing','Ryan Hall','770','Roswell'),
 ('Alpharetta Roof Co','Derek Young','770','Alpharetta'),
 ('Milton Roofing LLC','Brandon King','770','Milton'),
 ('Johns Creek Roof','Austin Turner','770','Johns Creek'),
 ('Duluth Roofing Pro','Tyler Scott','770','Duluth'),
 ('Norcross Roofing','Chad White','770','Norcross'),
 ('Lawrenceville Roof','Chris Adams','678','Lawrenceville'),
 ('Gwinnett Roofing','Mike Wilson','678','Lawrenceville'),
 ('Buford Roofing Co','Jason Green','770','Buford'),
 ('Cumming Roofing','Nathan Carter','770','Cumming'),
 ('Canton Roofing Pro','Greg Parker','770','Canton'),
 ('Woodstock Roofing','Blake Evans','770','Woodstock'),
 ('Cartersville Roof','Shane Morris','770','Cartersville'),
 ('Sandy Springs Roof','Logan Barnes','404','Sandy Springs'),
 ('Dunwoody Roofing','Garrett Price','770','Dunwoody'),
 ('Decatur Roof Pro','Travis Foster','404','Decatur'),
 ('Savannah Roofing','James Cooper','912','Savannah'),
 ('Coastal GA Roofing','William Russell','912','Savannah'),
 ('Augusta Roofing Co','Robert Hughes','706','Augusta'),
 ('Macon Roofing Pro','Thomas Griffin','478','Macon'),
 ('Columbus GA Roofing','David Jenkins','706','Columbus'),
 ('Albany Roofing LLC','Joseph Hayes','229','Albany'),
 ('Valdosta Roofing','Charles Ward','229','Valdosta'),
 ('Warner Robins Roof','Daniel Powell','478','Warner Robins'),
 ('Athens Roofing Co','Christopher Brooks','706','Athens'),
 ('Rome Roofing Pro','Kevin Sanders','706','Rome'),
 ('Gainesville GA Roof','Brian Long','770','Gainesville'),
 ('Dalton Roofing LLC','Scott Patterson','706','Dalton')
) AS t(c,n,ac,city);

-- ── OHIO (45) ─────────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'OH', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Columbus Roofing Co','Mark Henderson','614','Columbus'),
 ('Central Ohio Roofing','Kevin Walsh','614','Columbus'),
 ('Buckeye Roofing LLC','Brian Davis','614','Columbus'),
 ('Columbus Storm Pro','Ryan Miller','614','Columbus'),
 ('Dublin Roofing OH','Jason Thompson','614','Dublin'),
 ('Westerville Roof Co','Derek Nelson','614','Westerville'),
 ('Worthington Roofing','Austin Brown','614','Worthington'),
 ('Hilliard Roofing','Tyler Anderson','614','Hilliard'),
 ('Grove City Roof','Chad Johnson','614','Grove City'),
 ('Gahanna Roofing','Mike Williams','614','Gahanna'),
 ('New Albany Roof','Chris Lewis','614','New Albany'),
 ('Pickerington Roof','Matt Clark','614','Pickerington'),
 ('Canal Winchester','Steve Robinson','614','Canal Winchester'),
 ('Reynoldsburg Roof','Greg Martin','614','Reynoldsburg'),
 ('Pataskala Roofing','Scott Harris','740','Pataskala'),
 ('Cleveland Roof Pro','Frank Kowalski','216','Cleveland'),
 ('Cuyahoga Roofing','Tom Przybylski','216','Cleveland'),
 ('Cleveland Heights','Dan Stefanski','216','Cleveland Heights'),
 ('Parma Roofing LLC','Ed Wojcik','440','Parma'),
 ('Strongsville Roof','John Krauss','440','Strongsville'),
 ('North Olmsted Roof','Steve Novak','440','North Olmsted'),
 ('Lakewood OH Roofing','Mike Hornak','216','Lakewood'),
 ('Mentor Roofing Co','Paul Burkhart','440','Mentor'),
 ('Painesville Roof','Jim Lesnak','440','Painesville'),
 ('Lorain Roofing','Dave Blazek','440','Lorain'),
 ('Elyria Roof Pro','Bob Simonich','440','Elyria'),
 ('Westlake Roofing','Kevin Palko','440','Westlake'),
 ('Solon Roofing Co','Chris Mancini','440','Solon'),
 ('Berea Roofing','Mark Rosen','440','Berea'),
 ('Cincinnati Roofing','Eric Mueller','513','Cincinnati'),
 ('Queen City Roofing','Hans Weber','513','Cincinnati'),
 ('Blue Ash Roofing','Karl Schmidt','513','Blue Ash'),
 ('Mason OH Roofing','Fritz Bauer','513','Mason'),
 ('Fairfield Roofing','Otto Fischer','513','Fairfield'),
 ('West Chester Roof','Wilhelm Koch','513','West Chester'),
 ('Loveland OH Roof','Heinrich Wolf','513','Loveland'),
 ('Milford Roofing','Dieter Braun','513','Milford'),
 ('Akron Roofing Co','Bill Petroski','330','Akron'),
 ('Summit County Roof','Tony Zielinski','330','Akron'),
 ('Cuyahoga Falls','Mike Kaminski','330','Cuyahoga Falls'),
 ('Stow Roofing LLC','Dave Grabowski','330','Stow'),
 ('Barberton Roofing','Steve Wisniewski','330','Barberton'),
 ('Medina Roofing Pro','Tom Kowalczyk','330','Medina'),
 ('Canton Roofing OH','Jim Urbaniak','330','Canton'),
 ('Massillon Roof Co','Ed Szymanski','330','Massillon')
) AS t(c,n,ac,city);

-- ── ILLINOIS (40) ─────────────────────────────────────────────────────────────
INSERT INTO roofing_prospects
  (company_name, owner_name, email, phone, city, state, source, lead_score, source_detail, status, funnel_stage)
SELECT
  c, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(c,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  city, 'IL', 'manual_seed', (floor(random()*30+55))::int, 'exposure_machine_seed', 'new', 'new_lead'
FROM (VALUES
 ('Chicago Roofing Pros','Kevin Murphy','312','Chicago'),
 ('Windy City Roofing','Patrick O''Sullivan','773','Chicago'),
 ('North Shore Roofing','Brendan Fitzgerald','312','Chicago'),
 ('South Side Roofing','Sean Gallagher','773','Chicago'),
 ('West Chicago Roof','Michael O''Brien','708','Chicago'),
 ('Naperville Roofing','Brian Sullivan','630','Naperville'),
 ('Aurora IL Roofing','Ryan McCarthy','630','Aurora'),
 ('Joliet Roofing Co','Derek Callahan','815','Joliet'),
 ('Elgin Roofing LLC','Tyler Brennan','847','Elgin'),
 ('Schaumburg Roofing','Jason Donovan','847','Schaumburg'),
 ('Palatine Roof Pro','Chad Flanagan','847','Palatine'),
 ('Rolling Meadows','Mike Hannigan','847','Rolling Meadows'),
 ('Hoffman Estates','Greg O''Malley','847','Hoffman Estates'),
 ('Arlington Heights','Chris Hennessey','847','Arlington Heights'),
 ('Des Plaines Roof','Steve Mackey','847','Des Plaines'),
 ('Evanston Roofing','Jeff Sheridan','847','Evanston'),
 ('Skokie Roof Pro','Kevin Delaney','847','Skokie'),
 ('Niles Roofing LLC','Brian Donahue','847','Niles'),
 ('Park Ridge Roofing','Ryan Connelly','847','Park Ridge'),
 ('Glenview Roofing','Derek Brady','847','Glenview'),
 ('Northbrook Roofing','Tyler Burns','847','Northbrook'),
 ('Deerfield Roof Co','Austin Cain','847','Deerfield'),
 ('Libertyville Roof','Chad Farrell','847','Libertyville'),
 ('Vernon Hills Roof','Mike Garrity','847','Vernon Hills'),
 ('Waukegan Roofing','Greg Healy','847','Waukegan'),
 ('Bolingbrook Roof','Jason Ingram','630','Bolingbrook'),
 ('Romeoville Roof','Derek Joyce','815','Romeoville'),
 ('Plainfield IL Roof','Tyler Keane','815','Plainfield'),
 ('Mokena Roofing','Austin Lynch','708','Mokena'),
 ('Tinley Park Roof','Chad Madden','708','Tinley Park'),
 ('Orland Park Roofing','Mike Norman','708','Orland Park'),
 ('Frankfort Roofing','Greg O''Connor','815','Frankfort'),
 ('Lansing Roofing Co','Ryan Perry','708','Lansing'),
 ('Harvey Roof Pro','Derek Quinn','708','Harvey'),
 ('Rockford Roofing','Steve Riley','815','Rockford'),
 ('Loves Park Roof','Jeff Sheehan','815','Loves Park'),
 ('Peoria Roofing Co','Kevin Tanner','309','Peoria'),
 ('Springfield IL Roof','Brian Underwood','217','Springfield'),
 ('Champaign Roofing','Ryan Vaughan','217','Champaign'),
 ('Bloomington Roof','Derek Ward','309','Bloomington')
) AS t(c,n,ac,city);

-- ── NEXUS OUTBOUND PROSPECTS (200) ───────────────────────────────────────────
INSERT INTO nexus_outbound_prospects
  (business_name, owner_name, email, phone, industry, market, source, status)
SELECT
  b, n,
  lower(split_part(n,' ',1)) || '@' || lower(regexp_replace(b,'[^a-zA-Z0-9]','','g')) || '.com',
  '(' || ac || ') ' || (floor(random()*800+100))::int || '-' || lpad((floor(random()*9000+1000))::text,4,'0'),
  ind, mkt, 'manual_seed', 'new'
FROM (VALUES
 -- Real Estate / Property Management (40)
 ('Denver Property Group','Michael Torres','720','real_estate','Denver CO'),
 ('Mile High PM Co','Sarah Johnson','303','real_estate','Denver CO'),
 ('Front Range Properties','Kevin Anderson','720','real_estate','Denver CO'),
 ('Colorado PM Solutions','Brian Davis','303','real_estate','Denver CO'),
 ('Summit Property Mgmt','Ryan Wilson','720','real_estate','Denver CO'),
 ('Alpine Realty Group','Chris Martin','303','real_estate','Denver CO'),
 ('Rocky Mtn Rentals','Derek Thompson','720','real_estate','Denver CO'),
 ('Centennial PM','Tyler Brown','303','real_estate','Denver CO'),
 ('DFW Property Pros','Carlos Reyes','214','real_estate','Dallas TX'),
 ('Texas PM Group','James Martinez','817','real_estate','Fort Worth TX'),
 ('Lone Star Properties','Mike Hernandez','972','real_estate','Plano TX'),
 ('Houston PM Co','Eduardo Garcia','713','real_estate','Houston TX'),
 ('Gulf Coast Properties','Luis Rodriguez','832','real_estate','Houston TX'),
 ('Austin Realty Group','Matt Sullivan','512','real_estate','Austin TX'),
 ('SA Property Mgmt','Jose Gutierrez','210','real_estate','San Antonio TX'),
 ('Tampa Bay Properties','Carlos Mendez','813','real_estate','Tampa FL'),
 ('Sunshine Properties','Kevin Santos','727','real_estate','Tampa FL'),
 ('Central FL PM','James Wilson','407','real_estate','Orlando FL'),
 ('South Florida Props','Roberto Blanco','305','real_estate','Miami FL'),
 ('Jacksonville PM','Billy Harris','904','real_estate','Jacksonville FL'),
 ('ATL Property Group','Darius Jackson','404','real_estate','Atlanta GA'),
 ('Georgia PM Solutions','Marcus Brown','678','real_estate','Atlanta GA'),
 ('Peach State Props','Terrell Williams','404','real_estate','Atlanta GA'),
 ('Columbus OH Properties','Mark Henderson','614','real_estate','Columbus OH'),
 ('Ohio PM Group','Kevin Walsh','614','real_estate','Columbus OH'),
 ('Cleveland Properties','Frank Kowalski','216','real_estate','Cleveland OH'),
 ('Cincinnati PM Co','Eric Mueller','513','real_estate','Cincinnati OH'),
 ('Chicago Properties','Kevin Murphy','312','real_estate','Chicago IL'),
 ('Naperville PM','Brian Sullivan','630','real_estate','Naperville IL'),
 ('IL Property Mgmt','Ryan McCarthy','630','real_estate','Aurora IL'),
 ('Phoenix PM Group','Steve Larson','602','real_estate','Phoenix AZ'),
 ('Scottsdale Properties','Lisa Park','480','real_estate','Scottsdale AZ'),
 ('Las Vegas Properties','Mark Reynolds','702','real_estate','Las Vegas NV'),
 ('Portland PM Co','Jeff Barnes','503','real_estate','Portland OR'),
 ('Seattle Properties','Amy Chen','206','real_estate','Seattle WA'),
 ('Minneapolis PM','Tom Anderson','612','real_estate','Minneapolis MN'),
 ('Kansas City Props','Dave Miller','816','real_estate','Kansas City MO'),
 ('St Louis PM Group','Tim Roberts','314','real_estate','St Louis MO'),
 ('Indianapolis Props','Brad Thompson','317','real_estate','Indianapolis IN'),
 ('Nashville Properties','Craig Wilson','615','real_estate','Nashville TN'),
 -- Marketing Agencies (30)
 ('Apex Digital Agency','Jordan Blake','720','marketing_agency','Denver CO'),
 ('Peak Marketing Co','Alex Reed','303','marketing_agency','Denver CO'),
 ('Altitude Digital','Samantha Cruz','720','marketing_agency','Denver CO'),
 ('DFW Marketing Pros','Trevor Hall','214','marketing_agency','Dallas TX'),
 ('Texas Digital Agency','Nicole Lewis','817','marketing_agency','Fort Worth TX'),
 ('Houston Marketing Co','Diana Ramirez','713','marketing_agency','Houston TX'),
 ('Austin Digital Group','Patrick O''Brien','512','marketing_agency','Austin TX'),
 ('Tampa Digital Agency','Amanda Flores','813','marketing_agency','Tampa FL'),
 ('Orlando Marketing','Rachel Gutierrez','407','marketing_agency','Orlando FL'),
 ('ATL Digital Agency','Jasmine Williams','404','marketing_agency','Atlanta GA'),
 ('Columbus Marketing','Mike Henderson','614','marketing_agency','Columbus OH'),
 ('Cleveland Digital','Tom Kowalski','216','marketing_agency','Cleveland OH'),
 ('Chicago Marketing','Kelly Murphy','312','marketing_agency','Chicago IL'),
 ('Naperville Digital','Dan Sullivan','630','marketing_agency','Naperville IL'),
 ('Phoenix Digital Co','Ryan Larson','602','marketing_agency','Phoenix AZ'),
 ('Vegas Marketing','Amber Reynolds','702','marketing_agency','Las Vegas NV'),
 ('Portland Agency','Justin Barnes','503','marketing_agency','Portland OR'),
 ('Seattle Marketing','Jennifer Chen','206','marketing_agency','Seattle WA'),
 ('Minneapolis Agency','Travis Anderson','612','marketing_agency','Minneapolis MN'),
 ('Nashville Digital','Ashley Wilson','615','marketing_agency','Nashville TN'),
 ('Richmond Marketing','Derek Foster','804','marketing_agency','Richmond VA'),
 ('Charlotte Agency','Kyle Robertson','704','marketing_agency','Charlotte NC'),
 ('Raleigh Digital Co','Trent Coleman','919','marketing_agency','Raleigh NC'),
 ('Jacksonville Agency','Drew Patterson','904','marketing_agency','Jacksonville FL'),
 ('Miami Digital','Sofia Martinez','305','marketing_agency','Miami FL'),
 ('San Diego Marketing','Chase Hoffman','619','marketing_agency','San Diego CA'),
 ('Riverside Agency','Blake Wagner','951','marketing_agency','Riverside CA'),
 ('Sacramento Digital','Madison Lee','916','marketing_agency','Sacramento CA'),
 ('Omaha Marketing','Garrett Harris','402','marketing_agency','Omaha NE'),
 ('Tulsa Digital Agency','Cody Morgan','918','marketing_agency','Tulsa OK'),
 -- Consulting / Professional Services (40)
 ('Apex Business Consulting','Robert Kim','720','consulting','Denver CO'),
 ('Summit Advisors','Lisa Park','303','consulting','Denver CO'),
 ('Colorado Consulting','Brian Torres','720','consulting','Denver CO'),
 ('Peak Strategy Group','Kevin Walsh','303','consulting','Denver CO'),
 ('DFW Consulting Co','Carlos Rodriguez','214','consulting','Dallas TX'),
 ('Texas Strategy Group','James Lee','817','consulting','Fort Worth TX'),
 ('Houston Consulting','Eduardo Ramirez','713','consulting','Houston TX'),
 ('Austin Advisors','Matt Chen','512','consulting','Austin TX'),
 ('Tampa Consulting Co','Carlos Morales','813','consulting','Tampa FL'),
 ('Orlando Advisors','Ryan Santos','407','consulting','Orlando FL'),
 ('Miami Consulting','Roberto Cruz','305','consulting','Miami FL'),
 ('Atlanta Consulting','Darius Thompson','404','consulting','Atlanta GA'),
 ('Columbus Consulting','Mark Davis','614','consulting','Columbus OH'),
 ('Cleveland Advisors','Tom Stefanski','216','consulting','Cleveland OH'),
 ('Cincinnati Consulting','Eric Weber','513','consulting','Cincinnati OH'),
 ('Chicago Consulting','Kevin O''Brien','312','consulting','Chicago IL'),
 ('Naperville Advisors','Brian Fitzgerald','630','consulting','Naperville IL'),
 ('Phoenix Consulting','Steve Johnson','602','consulting','Phoenix AZ'),
 ('Vegas Consulting Co','Mark Williams','702','consulting','Las Vegas NV'),
 ('Seattle Advisors','Amy Nguyen','206','consulting','Seattle WA'),
 ('Portland Consulting','Jeff Taylor','503','consulting','Portland OR'),
 ('Minneapolis Advisors','Tom Peterson','612','consulting','Minneapolis MN'),
 ('Charlotte Consulting','Kyle Harris','704','consulting','Charlotte NC'),
 ('Nashville Advisors','Craig Brown','615','consulting','Nashville TN'),
 ('Indianapolis Consulting','Brad Miller','317','consulting','Indianapolis IN'),
 ('Kansas City Consulting','Dave Wilson','816','consulting','Kansas City MO'),
 ('St Louis Advisors','Tim Anderson','314','consulting','St Louis MO'),
 ('Omaha Consulting','Garrett Lewis','402','consulting','Omaha NE'),
 ('Tulsa Advisors','Cody Martin','918','consulting','Tulsa OK'),
 ('Oklahoma City Consulting','Tyler Davis','405','consulting','Oklahoma City OK'),
 ('San Antonio Consulting','Jose Hernandez','210','consulting','San Antonio TX'),
 ('El Paso Consulting','Marco Rodriguez','915','consulting','El Paso TX'),
 ('Albuquerque Advisors','Diego Sanchez','505','consulting','Albuquerque NM'),
 ('Salt Lake Consulting','Ryan Jensen','801','consulting','Salt Lake City UT'),
 ('Boise Consulting Co','Ty Morrison','208','consulting','Boise ID'),
 ('Spokane Advisors','Dan Christie','509','consulting','Spokane WA'),
 ('Reno Consulting','Mike Barnes','775','consulting','Reno NV'),
 ('Sacramento Advisors','Blake Lee','916','consulting','Sacramento CA'),
 ('Fresno Consulting','Chase Torres','559','consulting','Fresno CA'),
 ('Bakersfield Advisors','Travis Ramirez','661','consulting','Bakersfield CA'),
 -- HVAC / Plumbing / Trade Businesses (30)
 ('Front Range HVAC','Jason Miller','720','home_services','Denver CO'),
 ('Colorado HVAC Pros','Brian Nelson','303','home_services','Denver CO'),
 ('Denver Plumbing Co','Ryan Clark','303','home_services','Denver CO'),
 ('DFW HVAC Group','Carlos Torres','214','home_services','Dallas TX'),
 ('Texas Plumbing Pros','James Garcia','817','home_services','Fort Worth TX'),
 ('Houston HVAC Co','Eduardo Flores','713','home_services','Houston TX'),
 ('Tampa HVAC Group','Carlos Morales','813','home_services','Tampa FL'),
 ('Orlando Plumbing','Ryan Martinez','407','home_services','Orlando FL'),
 ('Atlanta HVAC Pros','Darius Williams','404','home_services','Atlanta GA'),
 ('Columbus HVAC Co','Mark Thompson','614','home_services','Columbus OH'),
 ('Cleveland Plumbing','Tom Novak','216','home_services','Cleveland OH'),
 ('Chicago HVAC Group','Kevin Ryan','312','home_services','Chicago IL'),
 ('Phoenix HVAC Pros','Steve Jensen','602','home_services','Phoenix AZ'),
 ('Vegas Plumbing Co','Mark Carson','702','home_services','Las Vegas NV'),
 ('Seattle HVAC Group','Amy Wu','206','home_services','Seattle WA'),
 ('Portland Plumbing','Jeff Mason','503','home_services','Portland OR'),
 ('Minneapolis HVAC','Tom Larsson','612','home_services','Minneapolis MN'),
 ('Nashville Plumbing','Craig Foster','615','home_services','Nashville TN'),
 ('Indianapolis HVAC','Brad Cooper','317','home_services','Indianapolis IN'),
 ('Kansas City HVAC','Dave Phillips','816','home_services','Kansas City MO'),
 ('Charlotte Plumbing','Kyle Rogers','704','home_services','Charlotte NC'),
 ('Raleigh HVAC Pros','Trent Patterson','919','home_services','Raleigh NC'),
 ('Richmond Plumbing','Derek Evans','804','home_services','Richmond VA'),
 ('Louisville HVAC','Chris Graham','502','home_services','Louisville KY'),
 ('Memphis Plumbing','Jason Brooks','901','home_services','Memphis TN'),
 ('Birmingham HVAC','Mike Crawford','205','home_services','Birmingham AL'),
 ('Jackson Plumbing','Brian Hughes','601','home_services','Jackson MS'),
 ('New Orleans HVAC','Ryan Stewart','504','home_services','New Orleans LA'),
 ('Baton Rouge Plumbing','Derek Cox','225','home_services','Baton Rouge LA'),
 ('Shreveport HVAC','Tyler Myers','318','home_services','Shreveport LA'),
 -- Landscaping / Restoration / Other Trades (30)
 ('Alpine Landscaping','Jason Green','720','landscaping','Denver CO'),
 ('Texas Landscaping Pro','Carlos Reyes','214','landscaping','Dallas TX'),
 ('Houston Lawn Co','Eduardo Garcia','713','landscaping','Houston TX'),
 ('Tampa Landscaping','Carlos Santos','813','landscaping','Tampa FL'),
 ('ATL Lawn Pros','Darius Brown','404','landscaping','Atlanta GA'),
 ('Columbus Landscaping','Mark Wilson','614','landscaping','Columbus OH'),
 ('Chicago Lawn Group','Kevin Walsh','312','landscaping','Chicago IL'),
 ('Phoenix Landscaping','Steve Brown','602','landscaping','Phoenix AZ'),
 ('Seattle Lawn Co','Amy Park','206','landscaping','Seattle WA'),
 ('Portland Landscaping','Jeff King','503','landscaping','Portland OR'),
 ('Denver Restoration Co','Brian Turner','720','restoration','Denver CO'),
 ('Texas Restoration','James Moore','214','restoration','Dallas TX'),
 ('Houston Restoration','Eduardo Rivera','713','restoration','Houston TX'),
 ('Tampa Restoration','Carlos Ortega','813','restoration','Tampa FL'),
 ('Atlanta Restoration','Darius Harris','404','restoration','Atlanta GA'),
 ('Columbus Restoration','Mark Nelson','614','restoration','Columbus OH'),
 ('Chicago Restoration','Kevin Brennan','312','restoration','Chicago IL'),
 ('Phoenix Restoration','Steve Taylor','602','restoration','Phoenix AZ'),
 ('Seattle Restoration','Amy Johnson','206','restoration','Seattle WA'),
 ('Portland Restoration','Jeff Anderson','503','restoration','Portland OR'),
 -- Insurance Agencies / Financial Services (30)
 ('Mile High Insurance','Michael Reed','720','insurance','Denver CO'),
 ('Colorado Insurance Co','Sarah Blake','303','insurance','Denver CO'),
 ('DFW Insurance Group','Trevor Ross','214','insurance','Dallas TX'),
 ('Texas Insurance Pros','Nicole Parker','817','insurance','Fort Worth TX'),
 ('Houston Insurance Co','Diana Wells','713','insurance','Houston TX'),
 ('Tampa Insurance Group','Amanda Rivera','813','insurance','Tampa FL'),
 ('ATL Insurance Pros','Jasmine Davis','404','insurance','Atlanta GA'),
 ('Columbus Insurance','Mike Foster','614','insurance','Columbus OH'),
 ('Chicago Insurance Co','Kelly Sullivan','312','insurance','Chicago IL'),
 ('Phoenix Insurance','Ryan Peterson','602','insurance','Phoenix AZ'),
 ('Denver Financial','Robert Torres','720','financial_services','Denver CO'),
 ('Texas Financial Co','Carlos Martin','214','financial_services','Dallas TX'),
 ('Houston Financial','Eduardo Torres','713','financial_services','Houston TX'),
 ('Tampa Financial Pro','Carlos Diaz','813','financial_services','Tampa FL'),
 ('ATL Financial Group','Darius Mitchell','404','financial_services','Atlanta GA'),
 ('Columbus Financial','Mark Lewis','614','financial_services','Columbus OH'),
 ('Chicago Financial','Kevin Gallagher','312','financial_services','Chicago IL'),
 ('Phoenix Financial','Steve Robinson','602','financial_services','Phoenix AZ'),
 ('Seattle Financial','Amy Thompson','206','financial_services','Seattle WA'),
 ('Nashville Financial','Craig Johnson','615','financial_services','Nashville TN'),
 ('Charlotte Financial','Kyle Williams','704','financial_services','Charlotte NC'),
 ('Indianapolis Financial','Brad Clark','317','financial_services','Indianapolis IN'),
 ('KC Financial Group','Dave Brown','816','financial_services','Kansas City MO'),
 ('St Louis Financial','Tim Davis','314','financial_services','St Louis MO'),
 ('Portland Financial','Jeff Garcia','503','financial_services','Portland OR'),
 ('Minneapolis Financial','Tom Anderson','612','financial_services','Minneapolis MO'),
 ('Omaha Financial Co','Garrett White','402','financial_services','Omaha NE'),
 ('Tulsa Financial Pro','Cody Harris','918','financial_services','Tulsa OK'),
 ('Albuquerque Financial','Diego Martinez','505','financial_services','Albuquerque NM'),
 ('Salt Lake Financial','Ryan Jensen','801','financial_services','Salt Lake City UT')
) AS t(b,n,ac,ind,mkt);
